export const ProductsData = [
    
    {
        id:1,
        Product: "realme P1 Pro 5G (Parrot Blue, 256 GB)",
        SellingPrice: "19,999",
        OriginalPrice: "25,999",
        Description: "8 GB RAM | 256 GB ROM",
        Display: "17.02 cm (6.7 inch) Full HD + Display",
        Camera: "50MP + 8MP | 16MP Front Camera",
        Battery: "5000 mAh Battery",
        Processor: "6 Gen 1 Processor",
        url: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/4/y/b/-original-imahyzygycuyg3mq.jpeg?q=70&crop=false",
        ratings: 4.5,
        reviews: 600,
        Discount: "upto 18500 off on Exchange",
        name:"Realme Mobile",
    },
    {
        id:2,
        Product: "realme P1 Pro 5G (Phoenix Red, 256 GB)",
        SellingPrice: "19,999",
        OriginalPrice: "25,999",
        Description: "8 GB RAM | 256 GB ROM",
        Display: "17.02 cm (6.7 inch) Full HD + Display",
        Camera: "50MP + 8MP | 16MP Front Camera",
        Battery: "5000 mAh Battery",
        Processor: "6 Gen 1 Processor",
        url: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/m/r/p/-original-imahyzygqydqtyvj.jpeg?q=70&crop=false",
        ratings: 4.5,
        reviews: 600,
        Discount: "upto 17500 off on Exchange",
        name:"Realme Mobile",
    },
    {
        id:3,
        Product: "Motorola Edge 50 fusion (Hot Pink, 128 GB)",
        SellingPrice: "22,999",
        OriginalPrice: "25,999",
        Description: "8 GB RAM | 128 GB ROM",
        Display: "17.02 cm (6.7 inch) Full HD + Display",
        Camera: "50MP + 13MP | 32MP Front Camera",
        Battery: "5000 mAh Battery",
        Processor: "7s Gen 2 Processor",
        url: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/i/k/l/edge-50-fusion-pb300001in-motorola-original-imahywzpfd2jh9ep.jpeg?q=70",
        ratings: 4.5,
        reviews: 1200,
        Discount: "upto 18500 off on Exchange",
        name:"Moto Phone",
    },
    {
        id:4,
        Product: "Motorola Edge 50 fusion (Marshmallow Blue, 256 GB)",
        SellingPrice: "24,999",
        OriginalPrice: "27,999",
        Description: "12 GB RAM | 256 GB ROM",
        Display: "17.02 cm (6.7 inch) Full HD + Display",
        Camera: "50MP + 13MP | 32MP Front Camera",
        Battery: "5000 mAh Battery",
        Processor: "7s Gen 2 Processor",
        url: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/5/t/j/edge-50-fusion-pb300002in-motorola-original-imahywzrfagkuyxx.jpeg?q=70",
        ratings: 4.5,
        reviews: 1200,
        Discount: "upto 22500 off on Exchange",
        name:"Moto Phone",
    },

]

export const WatchProduct = [
    {
        id:1,
        Product:"2046 BK Day and Date Analog Watch",
        name: "Watch",
        Brand: "FOGG",
        Selling_Price:"329",
        Original_Price:"1499",
        Discount:"78% off",
        ratings:4.5,
        reviews:1000,
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/c/v/x/1-2046-bk-fogg-men-original-imahfqxbgazsdmzb.jpeg?q=70",
    },
    {
        id:2,
        Product:"Briggs Analog Watch",
        name: "Watch",
        Brand: "FOSSIL",
        Selling_Price:"4498",
        Original_Price:"9995",
        Discount:"54% off",
        ratings:4.5,
        reviews:1000,
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/z/p/c/-original-imagpzjfgmbpmscn.jpeg?q=70", 
    },
    {
        id:3,
        Product:"Grant Spor Analog Watch",
        name: "Watch",
        Brand: "FOSSIL",
        Selling_Price:"5623",
        Original_Price:"2495",
        Discount:"54% off",
        ratings:4.5,
        reviews:1000,
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/j/j/y/-original-imagt7fhhkt7zzwm.jpeg?q=70",
    },

];